baseURL = "https://jarynote.cn"
title = "Fusing"
author = "Jianyue SU"
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']
copyright = "上述产品为本公司所有，具有最终解释权"

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = false

  [params.logo]
    main = "img/logo/logo1.png"
    alt = "Fusing Logo"
    
    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-10 w-10"

  [params.site]
    name = "Fusing"
  [params.sidebar]
    about = "欢迎访问" 
  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true
  
  [params.homepage_meta_tags]
    meta_description = "1111111111111111111111"
    meta_og_title = "Tella"
    meta_og_type = "website"
    meta_og_url = "img/slide/slide01.jpg"
    meta_og_image = "img/slide/slide02.jpg"
    meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."


[menu]

  [[menu.main]]
    identifier = "products"
    name = "产品"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "品牌介绍"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "联系"
    url = "/contact/"
    weight = 4
  # Footer Menu
  [[menu.footer]]
    name = "主页"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
